version: "2"
services:
  node:
#    build:
#      context: .
    image: vlakam/webm2mp4-telegram-bot
    env_file:
      .env
    restart: always
    depends_on:
      - mongo
    networks:
      - database_nw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  mongo:
    restart: always
    image: mongo:latest
    volumes:
      - mongo-db:/data/db
    networks:
      - database_nw
#    ports:
#      - 27017:27017
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  database_nw:
    driver: bridge

volumes:
  mongo-db:
    driver: 'local'
