version: "2"
services:
  node:
    build:
     context: .
    env_file:
      .env.local.docker
    restart: always
    volumes:
      - cache-data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  cache-data:
    driver: 'local'
